# Generated by Django 5.2.3 on 2025-06-25 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='user_type',
            field=models.CharField(default='doctor', max_length=10),
            preserve_default=False,
        ),
    ]
