# Generated by Django 5.2.3 on 2025-06-25 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_myuser_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
