# Generated by Django 5.2.3 on 2025-09-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
