# Generated by Django 5.2.3 on 2025-09-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_patient_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('General', 'General'), ('Cardiology', 'Cardiology'), ('Neurology', 'Neurology'), ('ENT', 'ENT'), ('Orthopedics', 'Orthopedics'), ('Pediatrics', 'Pediatrics'), ('Dermatology', 'Dermatology')], default='General', max_length=50),
        ),
    ]
